language: csharp
dist: trusty
mono: none
dotnet: 2.1.502
script:
  - dotnet tool install paket -g
  - paket restore
  - dotnet restore
  - dotnet build
  - dotnet publish -c release
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: src/ftafl.Client/bin/Release/netstandard2.0/publish/ftafl.Client/dist
  on:
    branch: master