language: csharp
dist: trusty
mono: none
dotnet: 2.1.502
script:
  - dotnet tool install paket --tool-path .paket
  - cd src/ftafl.Client.JS
  - dotnet tool install paket --tool-path .paket
  - cd src
  - dotnet restore
  #- dotnet build
  #- dotnet publish -c release
  - dotnet fable yarn-build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  #local-dir: src/ftafl.Client/bin/Release/netstandard2.0/publish/ftafl.Client/dist
  local-dir: src/ftafl.Client.JS/public
  on:
    branch: master